### ISSUE TITLE
[error] Parameter 'commandLine' cannot be null or empty.

### ISSUE THREAD

**Issue by davivcgarcia** [denolib/setup-deno#51]
When using the action:

```yaml
    - name: (API) Setup Deno environment
      uses: denolib/setup-deno@v2
      with:
        deno-version: v1.x
```
On a `self-hosted` runner, I see the following error:

```bash
Run denolib/setup-deno@v2
  with:
    deno-version: v1.x
##[error]Parameter 'commandLine' cannot be null or empty.
```
Any advice?

**Comment by davivcgarcia** [comment]
The error seems to be generated here:

https://github.com/denolib/setup-deno/blob/482dc739be8628399f8b04bd11876f7d9a24f625/dist/index.js#L4754-L4766

**Comment by zhmushan** [comment]
https://github.com/denolib/setup-deno/blob/482dc739be8628399f8b04bd11876f7d9a24f625/src/installer.ts#L193-L194

Is there `gzip` in `self-hosted`?

**Comment by axetroy** [comment]
> https://github.com/denolib/setup-deno/blob/482dc739be8628399f8b04bd11876f7d9a24f625/src/installer.ts#L193-L194
> 
> Is there `gzip` in `self-hosted`?

This is indeed a problem, we should use the zip implemented in pure nodejs

**Comment by davivcgarcia** [comment]
> https://github.com/denolib/setup-deno/blob/482dc739be8628399f8b04bd11876f7d9a24f625/src/installer.ts#L193-L194
> 
> Is there `gzip` in `self-hosted`?

Yes, I do.

```
[root@ip-172-31-52-214 ec2-user]# rpm -qa | grep gzip
gzip-1.9-9.el8.x86_64
[root@ip-172-31-52-214 ec2-user]# cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.2 (Ootpa)
```

**Comment by davivcgarcia** [comment]
What are the other packages required for this action? I can check if all of them are properly installed.

**Comment by zhmushan** [comment]
I just tested `self-hosted`, using Linux x64 environment, and successfully executed `setup-deno`🤔

**Comment by davivcgarcia** [comment]
> I just tested `self-hosted`, using Linux x64 environment, and successfully executed `setup-deno`thinking

What distribution did you use? I'm using a CentOs/RHEL 8 minimum install.

**Comment by jameskerr** [comment]
I too am experiencing this same error on a centos:8 docker container.

```
 /usr/bin/docker exec  1ac4a3ce3754dfaeeb0c7d6f38d7328f4d0621d78d43bf54890ebd4ab7adea87 sh -c "cat /etc/*release | grep ^ID"
##[error]Parameter 'commandLine' cannot be null or empty.
```

**Comment by jameskerr** [comment]
Is the issue that on Centos 8 containers, `await io.which("gzip")` is returning an empty string? 
Then when that empty string is passed to `exec.exec()` we get that argument error?

https://github.com/denolib/setup-deno/blob/482dc739be8628399f8b04bd11876f7d9a24f625/src/installer.ts#L193-L194

**Comment by zhmushan** [comment]
> Is the issue that on Centos 8 containers, `await io.which("gzip")` is returning an empty string?
> Then when that empty string is passed to `exec.exec()` we get that argument error?
> 
> https://github.com/denolib/setup-deno/blob/482dc739be8628399f8b04bd11876f7d9a24f625/src/installer.ts#L193-L194

I suspect yes, I need to verify on CentOS, but it will take a few days.
Anyway, `gzip` implemented using pure `nodejs` is necessary

**Comment by jameskerr** [comment]
I found a way to get this action to work on Centos 8 containers. Before running this action, install the unzip package using dnf.

```
dnf install -y unzip
```

The workflow file that worked for me was:

```yml
name: Deno Install Test
on: [push]

jobs:
  install:
    name: "Deno Install"
    runs-on: ubuntu-18.04
    container:
      image: centos:8
    steps:
      - run: dnf install -y unzip
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - run: deno --version

```
