### ISSUE TITLE
Add ~/.deno/lib/ To PATH

### ISSUE THREAD

**Issue by oganexon** [denolib/setup-deno#67]
When installing a deno module globally, I am unable to use the exec in other steps
```yaml
- run: deno install -A -n foo mod.ts

- run: foo
```
``` 
 /home/runner/work/_temp/013c1727-ed4e-4aa8-aca7-9e9ae2257aff.sh: line 1: foo: command not found
```

However it works if I add /.deno/bin/ to the PATH it works 
On Linux: 
```yaml
- run: |
  deno install -A -n foo mod.ts
  echo "::add-path::/home/runner/.deno/bin"

- run: foo
```

Is it possible to add /.deno/bin/ to the PATH by default on the action?
