### ISSUE TITLE
Support Deno canary channel

### ISSUE THREAD

**Issue by zhmushan** [denolib/setup-deno#76]
From https://github.com/denolib/setup-deno/issues/47#issuecomment-736301440

```yml
steps:
  - uses: denolib/setup-deno@v3
    with:
      deno-version: 973af61d8bb03c1709f61e456581d58386ed4952
      deno-canary: true
```

**Comment by axetroy** [comment]
It seems that deno-canary is redundant

We can check whether it is a hash from deno-version

```diff
steps:
  - uses: denolib/setup-deno@v3
    with:
      deno-version: 973af61d8bb03c1709f61e456581d58386ed4952
-      deno-canary: true
```

**Comment by zhmushan** [comment]
If `deno-canary` is set, users can omit `deno-version` to get the latest canary release

**Comment by maximousblk** [comment]
you can also do: set `deno-canary` to `canary` to get latest canary. similar to `nightly`.

**Comment by lucacasonato** [comment]
I would prefer that actually.
```
steps:
  - uses: denolib/setup-deno@v3
    with:
      deno-version: canary
```
```
steps:
  - uses: denolib/setup-deno@v3
    with:
      deno-version: 973af61d8bb03c1709f61e456581d58386ed4952
```

**Comment by axetroy** [comment]
I personally prefer not to bring any BREAKING CHANGES.

I want users to always use v2.

Especially this PR(https://github.com/actions/starter-workflows/pull/604) have been merged.

```yml
steps:
  - uses: denolib/setup-deno@v2
    with:
      deno-version: canary
      # canary = nightly
      # deno-version: nightly
      # deno-version: <HASH>
```

Just need to do two things

1. Support HASH
2. Use nightly as an alias for canary, and it is no longer recommended in the document, and output a warning when 
 using.

**Comment by maximousblk** [comment]
I don't think keeping the version at v2 would help with https://github.com/actions/starter-workflows/pull/604 as it locked to a commit hash rather than a tag.

I'd suggest go forward with the breaking change and even phase out nightly as it was a temporary solution until it was official. My nightly solution is prone to breaking and has many builds missing because of refactors in deno's code that I didn't catch in time. the reason `setup-deno` didn't broke was that I had a `latest` tag which would always have the latest available build even if the workflow broke.


imo v3 should be:

```yml

# Latest version
- uses: denolib/setup-deno@v2

# Latest version in a range
- uses: denolib/setup-deno@v2
  with:
    version: 1.5 # (resolve to 1.5.4)

# Locked version
- uses: denolib/setup-deno@v2
  with:
    version: 1.5.4

# Latest canary
- uses: denolib/setup-deno@v2
  with:
    version: canary

# Locked canary
- uses: denolib/setup-deno@v2
  with:
    version: 5f05e1783e9f08d1be4b71f2099601458da78dcd

```
